export const GET_STUDENT = "GET_STUDENT";
export const INCREMENT_ATTENDANCE = "INCREMENT_ATTENDANCE";
export const DECREMENT_ATTENDANCE = "DECREMENT_ATTENDANCE";
export const TOGGLE_ORDER_NOTES = 'TOGGLE_ORDER_NOTES';
export const RESET = 'RESET';
export const SET_BEHAVIOURS = 'SET_BEHAVIOURS';